### ISSUE TITLE
SMS campaign

### ISSUE THREAD

**Issue by emmguyot-adscom** [LoicLEMEUT/sendinblue#1]
Do you plan to implement SMS campaign in this module ?

**Comment by LoicLEMEUT** [comment]
Hi, sorry for my delayed answer !

For the moment, no, i don't have plan to implements sms campaign: I just port this module from Drupal 7 to Drupal 8.

But it's a good idea ! I will search a solution for that this Week-end.

Loïc LE MEUT

**Comment by emmguyot-adscom** [comment]
Ok, thank you for your answer.

**Comment by LoicLEMEUT** [comment]
Hi,

I just search a solution for SMS campaign. With this module, you can add contacts to a specific Sendinblue list thanks to signup forms.

After that, you can send SMS campaigns with your specific list. There is an interface for manage campaigns and lists inside module.

What do you want to do exactly ?

**Comment by emmguyot-adscom** [comment]
Hi,

I was looking for a module that would increment both newsletter and SMS campaign list with SendInBlue.
Though, your last answer explains that there isn't any specific need to increment a SMS campaign. So this issue can be closed.
